# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake

# The command to remove a file.
RM = /beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /beegfs/teran_parrales/NVISII

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /beegfs/teran_parrales/NVISII

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.0.1-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/beegfs/Tools/easybuild/stacks/rome/2022a/software/CMake/3.23.1-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /beegfs/teran_parrales/NVISII/CMakeFiles /beegfs/teran_parrales/NVISII//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /beegfs/teran_parrales/NVISII/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nvisii_lib

# Build rule for target.
nvisii_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvisii_lib
.PHONY : nvisii_lib

# fast build rule for target.
nvisii_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/build
.PHONY : nvisii_lib/fast

#=============================================================================
# Target rules for targets named nvisii

# Build rule for target.
nvisii: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvisii
.PHONY : nvisii

# fast build rule for target.
nvisii/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii.dir/build.make CMakeFiles/nvisii.dir/build
.PHONY : nvisii/fast

#=============================================================================
# Target rules for targets named nvisii_swig_compilation

# Build rule for target.
nvisii_swig_compilation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvisii_swig_compilation
.PHONY : nvisii_swig_compilation

# fast build rule for target.
nvisii_swig_compilation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_swig_compilation.dir/build.make CMakeFiles/nvisii_swig_compilation.dir/build
.PHONY : nvisii_swig_compilation/fast

#=============================================================================
# Target rules for targets named generator

# Build rule for target.
generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generator
.PHONY : generator

# fast build rule for target.
generator/fast:
	$(MAKE) $(MAKESILENT) -f externals/generator/src/CMakeFiles/generator.dir/build.make externals/generator/src/CMakeFiles/generator.dir/build
.PHONY : generator/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f externals/glfw/src/CMakeFiles/glfw.dir/build.make externals/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f externals/assimp/code/CMakeFiles/assimp.dir/build.make externals/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named owl_static

# Build rule for target.
owl_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 owl_static
.PHONY : owl_static

# fast build rule for target.
owl_static/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/owl/CMakeFiles/owl_static.dir/build.make externals/owl/owl/CMakeFiles/owl_static.dir/build
.PHONY : owl_static/fast

#=============================================================================
# Target rules for targets named sample00-rayGenOnly

# Build rule for target.
sample00-rayGenOnly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample00-rayGenOnly
.PHONY : sample00-rayGenOnly

# fast build rule for target.
sample00-rayGenOnly/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s00-rayGenOnly/CMakeFiles/sample00-rayGenOnly.dir/build.make externals/owl/samples/cmdline/s00-rayGenOnly/CMakeFiles/sample00-rayGenOnly.dir/build
.PHONY : sample00-rayGenOnly/fast

#=============================================================================
# Target rules for targets named sample01-simpleTriangles

# Build rule for target.
sample01-simpleTriangles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample01-simpleTriangles
.PHONY : sample01-simpleTriangles

# fast build rule for target.
sample01-simpleTriangles/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s01-simpleTriangles/CMakeFiles/sample01-simpleTriangles.dir/build.make externals/owl/samples/cmdline/s01-simpleTriangles/CMakeFiles/sample01-simpleTriangles.dir/build
.PHONY : sample01-simpleTriangles/fast

#=============================================================================
# Target rules for targets named sample05-rtow

# Build rule for target.
sample05-rtow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample05-rtow
.PHONY : sample05-rtow

# fast build rule for target.
sample05-rtow/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s05-rtow/CMakeFiles/sample05-rtow.dir/build.make externals/owl/samples/cmdline/s05-rtow/CMakeFiles/sample05-rtow.dir/build
.PHONY : sample05-rtow/fast

#=============================================================================
# Target rules for targets named sample06-rtow-mixedGeometries

# Build rule for target.
sample06-rtow-mixedGeometries: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample06-rtow-mixedGeometries
.PHONY : sample06-rtow-mixedGeometries

# fast build rule for target.
sample06-rtow-mixedGeometries/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s06-rtow-mixedGeometries/CMakeFiles/sample06-rtow-mixedGeometries.dir/build.make externals/owl/samples/cmdline/s06-rtow-mixedGeometries/CMakeFiles/sample06-rtow-mixedGeometries.dir/build
.PHONY : sample06-rtow-mixedGeometries/fast

#=============================================================================
# Target rules for targets named sample07-rtow-multiGPU

# Build rule for target.
sample07-rtow-multiGPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample07-rtow-multiGPU
.PHONY : sample07-rtow-multiGPU

# fast build rule for target.
sample07-rtow-multiGPU/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s07-rtow-multiGPU/CMakeFiles/sample07-rtow-multiGPU.dir/build.make externals/owl/samples/cmdline/s07-rtow-multiGPU/CMakeFiles/sample07-rtow-multiGPU.dir/build
.PHONY : sample07-rtow-multiGPU/fast

#=============================================================================
# Target rules for targets named sample08-sierpinski

# Build rule for target.
sample08-sierpinski: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample08-sierpinski
.PHONY : sample08-sierpinski

# fast build rule for target.
sample08-sierpinski/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s08-sierpinski/CMakeFiles/sample08-sierpinski.dir/build.make externals/owl/samples/cmdline/s08-sierpinski/CMakeFiles/sample08-sierpinski.dir/build
.PHONY : sample08-sierpinski/fast

#=============================================================================
# Target rules for targets named sample09-motionBlurSimpleTriangles

# Build rule for target.
sample09-motionBlurSimpleTriangles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample09-motionBlurSimpleTriangles
.PHONY : sample09-motionBlurSimpleTriangles

# fast build rule for target.
sample09-motionBlurSimpleTriangles/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/cmdline/s09-motionBlurSimpleTriangles/CMakeFiles/sample09-motionBlurSimpleTriangles.dir/build.make externals/owl/samples/cmdline/s09-motionBlurSimpleTriangles/CMakeFiles/sample09-motionBlurSimpleTriangles.dir/build
.PHONY : sample09-motionBlurSimpleTriangles/fast

#=============================================================================
# Target rules for targets named owl_viewer

# Build rule for target.
owl_viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 owl_viewer
.PHONY : owl_viewer

# fast build rule for target.
owl_viewer/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/common/owlViewer/CMakeFiles/owl_viewer.dir/build.make externals/owl/samples/common/owlViewer/CMakeFiles/owl_viewer.dir/build
.PHONY : owl_viewer/fast

#=============================================================================
# Target rules for targets named int01-simpleTriangles

# Build rule for target.
int01-simpleTriangles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 int01-simpleTriangles
.PHONY : int01-simpleTriangles

# fast build rule for target.
int01-simpleTriangles/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/interactive/int01-simpleTriangles/CMakeFiles/int01-simpleTriangles.dir/build.make externals/owl/samples/interactive/int01-simpleTriangles/CMakeFiles/int01-simpleTriangles.dir/build
.PHONY : int01-simpleTriangles/fast

#=============================================================================
# Target rules for targets named int06-rtow-mixedGeometries

# Build rule for target.
int06-rtow-mixedGeometries: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 int06-rtow-mixedGeometries
.PHONY : int06-rtow-mixedGeometries

# fast build rule for target.
int06-rtow-mixedGeometries/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/interactive/int06-mixedGeometries/CMakeFiles/int06-rtow-mixedGeometries.dir/build.make externals/owl/samples/interactive/int06-mixedGeometries/CMakeFiles/int06-rtow-mixedGeometries.dir/build
.PHONY : int06-rtow-mixedGeometries/fast

#=============================================================================
# Target rules for targets named int10-texturedTriangles

# Build rule for target.
int10-texturedTriangles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 int10-texturedTriangles
.PHONY : int10-texturedTriangles

# fast build rule for target.
int10-texturedTriangles/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/interactive/int10-texturedTriangles/CMakeFiles/int10-texturedTriangles.dir/build.make externals/owl/samples/interactive/int10-texturedTriangles/CMakeFiles/int10-texturedTriangles.dir/build
.PHONY : int10-texturedTriangles/fast

#=============================================================================
# Target rules for targets named int11-rotatingBoxes

# Build rule for target.
int11-rotatingBoxes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 int11-rotatingBoxes
.PHONY : int11-rotatingBoxes

# fast build rule for target.
int11-rotatingBoxes/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/interactive/int11-rotatingBoxes/CMakeFiles/int11-rotatingBoxes.dir/build.make externals/owl/samples/interactive/int11-rotatingBoxes/CMakeFiles/int11-rotatingBoxes.dir/build
.PHONY : int11-rotatingBoxes/fast

#=============================================================================
# Target rules for targets named int12-switchingTextureSets

# Build rule for target.
int12-switchingTextureSets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 int12-switchingTextureSets
.PHONY : int12-switchingTextureSets

# fast build rule for target.
int12-switchingTextureSets/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/interactive/int12-switchingTextureSets/CMakeFiles/int12-switchingTextureSets.dir/build.make externals/owl/samples/interactive/int12-switchingTextureSets/CMakeFiles/int12-switchingTextureSets.dir/build
.PHONY : int12-switchingTextureSets/fast

#=============================================================================
# Target rules for targets named int13-motionBlurBoxes

# Build rule for target.
int13-motionBlurBoxes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 int13-motionBlurBoxes
.PHONY : int13-motionBlurBoxes

# fast build rule for target.
int13-motionBlurBoxes/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/interactive/int13-motionBlurInstances/CMakeFiles/int13-motionBlurBoxes.dir/build.make externals/owl/samples/interactive/int13-motionBlurInstances/CMakeFiles/int13-motionBlurBoxes.dir/build
.PHONY : int13-motionBlurBoxes/fast

#=============================================================================
# Target rules for targets named toneMap

# Build rule for target.
toneMap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 toneMap
.PHONY : toneMap

# fast build rule for target.
toneMap/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/advanced/optix7course/CMakeFiles/toneMap.dir/build.make externals/owl/samples/advanced/optix7course/CMakeFiles/toneMap.dir/build
.PHONY : toneMap/fast

#=============================================================================
# Target rules for targets named adv_optix7course

# Build rule for target.
adv_optix7course: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 adv_optix7course
.PHONY : adv_optix7course

# fast build rule for target.
adv_optix7course/fast:
	$(MAKE) $(MAKESILENT) -f externals/owl/samples/advanced/optix7course/CMakeFiles/adv_optix7course.dir/build.make externals/owl/samples/advanced/optix7course/CMakeFiles/adv_optix7course.dir/build
.PHONY : adv_optix7course/fast

CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.o: CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.o
.PHONY : CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.o

# target to build an object file
CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii.dir/build.make CMakeFiles/nvisii.dir/CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.o
.PHONY : CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.o

CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.i: CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.i
.PHONY : CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.i

# target to preprocess a source file
CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii.dir/build.make CMakeFiles/nvisii.dir/CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.i
.PHONY : CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.i

CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.s: CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.s
.PHONY : CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.s

# target to generate assembly for a file
CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii.dir/build.make CMakeFiles/nvisii.dir/CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.s
.PHONY : CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.cxx.s

cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.o: cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.o
.PHONY : cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.o

# target to build an object file
cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.o
.PHONY : cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.o

cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.i: cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.i
.PHONY : cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.i

# target to preprocess a source file
cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.i
.PHONY : cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.i

cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.s: cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.s
.PHONY : cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.s

# target to generate assembly for a file
cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.s
.PHONY : cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.c.s

externals/glad/src/glad.o: externals/glad/src/glad.c.o
.PHONY : externals/glad/src/glad.o

# target to build an object file
externals/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/glad/src/glad.c.o
.PHONY : externals/glad/src/glad.c.o

externals/glad/src/glad.i: externals/glad/src/glad.c.i
.PHONY : externals/glad/src/glad.i

# target to preprocess a source file
externals/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/glad/src/glad.c.i
.PHONY : externals/glad/src/glad.c.i

externals/glad/src/glad.s: externals/glad/src/glad.c.s
.PHONY : externals/glad/src/glad.s

# target to generate assembly for a file
externals/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/glad/src/glad.c.s
.PHONY : externals/glad/src/glad.c.s

externals/imgui/ImCurveEdit.o: externals/imgui/ImCurveEdit.cpp.o
.PHONY : externals/imgui/ImCurveEdit.o

# target to build an object file
externals/imgui/ImCurveEdit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImCurveEdit.cpp.o
.PHONY : externals/imgui/ImCurveEdit.cpp.o

externals/imgui/ImCurveEdit.i: externals/imgui/ImCurveEdit.cpp.i
.PHONY : externals/imgui/ImCurveEdit.i

# target to preprocess a source file
externals/imgui/ImCurveEdit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImCurveEdit.cpp.i
.PHONY : externals/imgui/ImCurveEdit.cpp.i

externals/imgui/ImCurveEdit.s: externals/imgui/ImCurveEdit.cpp.s
.PHONY : externals/imgui/ImCurveEdit.s

# target to generate assembly for a file
externals/imgui/ImCurveEdit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImCurveEdit.cpp.s
.PHONY : externals/imgui/ImCurveEdit.cpp.s

externals/imgui/ImGradient.o: externals/imgui/ImGradient.cpp.o
.PHONY : externals/imgui/ImGradient.o

# target to build an object file
externals/imgui/ImGradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImGradient.cpp.o
.PHONY : externals/imgui/ImGradient.cpp.o

externals/imgui/ImGradient.i: externals/imgui/ImGradient.cpp.i
.PHONY : externals/imgui/ImGradient.i

# target to preprocess a source file
externals/imgui/ImGradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImGradient.cpp.i
.PHONY : externals/imgui/ImGradient.cpp.i

externals/imgui/ImGradient.s: externals/imgui/ImGradient.cpp.s
.PHONY : externals/imgui/ImGradient.s

# target to generate assembly for a file
externals/imgui/ImGradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImGradient.cpp.s
.PHONY : externals/imgui/ImGradient.cpp.s

externals/imgui/ImGuizmo.o: externals/imgui/ImGuizmo.cpp.o
.PHONY : externals/imgui/ImGuizmo.o

# target to build an object file
externals/imgui/ImGuizmo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImGuizmo.cpp.o
.PHONY : externals/imgui/ImGuizmo.cpp.o

externals/imgui/ImGuizmo.i: externals/imgui/ImGuizmo.cpp.i
.PHONY : externals/imgui/ImGuizmo.i

# target to preprocess a source file
externals/imgui/ImGuizmo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImGuizmo.cpp.i
.PHONY : externals/imgui/ImGuizmo.cpp.i

externals/imgui/ImGuizmo.s: externals/imgui/ImGuizmo.cpp.s
.PHONY : externals/imgui/ImGuizmo.s

# target to generate assembly for a file
externals/imgui/ImGuizmo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImGuizmo.cpp.s
.PHONY : externals/imgui/ImGuizmo.cpp.s

externals/imgui/ImSequencer.o: externals/imgui/ImSequencer.cpp.o
.PHONY : externals/imgui/ImSequencer.o

# target to build an object file
externals/imgui/ImSequencer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImSequencer.cpp.o
.PHONY : externals/imgui/ImSequencer.cpp.o

externals/imgui/ImSequencer.i: externals/imgui/ImSequencer.cpp.i
.PHONY : externals/imgui/ImSequencer.i

# target to preprocess a source file
externals/imgui/ImSequencer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImSequencer.cpp.i
.PHONY : externals/imgui/ImSequencer.cpp.i

externals/imgui/ImSequencer.s: externals/imgui/ImSequencer.cpp.s
.PHONY : externals/imgui/ImSequencer.s

# target to generate assembly for a file
externals/imgui/ImSequencer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/ImSequencer.cpp.s
.PHONY : externals/imgui/ImSequencer.cpp.s

externals/imgui/imgui.o: externals/imgui/imgui.cpp.o
.PHONY : externals/imgui/imgui.o

# target to build an object file
externals/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui.cpp.o
.PHONY : externals/imgui/imgui.cpp.o

externals/imgui/imgui.i: externals/imgui/imgui.cpp.i
.PHONY : externals/imgui/imgui.i

# target to preprocess a source file
externals/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui.cpp.i
.PHONY : externals/imgui/imgui.cpp.i

externals/imgui/imgui.s: externals/imgui/imgui.cpp.s
.PHONY : externals/imgui/imgui.s

# target to generate assembly for a file
externals/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui.cpp.s
.PHONY : externals/imgui/imgui.cpp.s

externals/imgui/imgui_demo.o: externals/imgui/imgui_demo.cpp.o
.PHONY : externals/imgui/imgui_demo.o

# target to build an object file
externals/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_demo.cpp.o
.PHONY : externals/imgui/imgui_demo.cpp.o

externals/imgui/imgui_demo.i: externals/imgui/imgui_demo.cpp.i
.PHONY : externals/imgui/imgui_demo.i

# target to preprocess a source file
externals/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_demo.cpp.i
.PHONY : externals/imgui/imgui_demo.cpp.i

externals/imgui/imgui_demo.s: externals/imgui/imgui_demo.cpp.s
.PHONY : externals/imgui/imgui_demo.s

# target to generate assembly for a file
externals/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_demo.cpp.s
.PHONY : externals/imgui/imgui_demo.cpp.s

externals/imgui/imgui_draw.o: externals/imgui/imgui_draw.cpp.o
.PHONY : externals/imgui/imgui_draw.o

# target to build an object file
externals/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_draw.cpp.o
.PHONY : externals/imgui/imgui_draw.cpp.o

externals/imgui/imgui_draw.i: externals/imgui/imgui_draw.cpp.i
.PHONY : externals/imgui/imgui_draw.i

# target to preprocess a source file
externals/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_draw.cpp.i
.PHONY : externals/imgui/imgui_draw.cpp.i

externals/imgui/imgui_draw.s: externals/imgui/imgui_draw.cpp.s
.PHONY : externals/imgui/imgui_draw.s

# target to generate assembly for a file
externals/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_draw.cpp.s
.PHONY : externals/imgui/imgui_draw.cpp.s

externals/imgui/imgui_impl_glfw.o: externals/imgui/imgui_impl_glfw.cpp.o
.PHONY : externals/imgui/imgui_impl_glfw.o

# target to build an object file
externals/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_impl_glfw.cpp.o
.PHONY : externals/imgui/imgui_impl_glfw.cpp.o

externals/imgui/imgui_impl_glfw.i: externals/imgui/imgui_impl_glfw.cpp.i
.PHONY : externals/imgui/imgui_impl_glfw.i

# target to preprocess a source file
externals/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_impl_glfw.cpp.i
.PHONY : externals/imgui/imgui_impl_glfw.cpp.i

externals/imgui/imgui_impl_glfw.s: externals/imgui/imgui_impl_glfw.cpp.s
.PHONY : externals/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
externals/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_impl_glfw.cpp.s
.PHONY : externals/imgui/imgui_impl_glfw.cpp.s

externals/imgui/imgui_impl_opengl3.o: externals/imgui/imgui_impl_opengl3.cpp.o
.PHONY : externals/imgui/imgui_impl_opengl3.o

# target to build an object file
externals/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_impl_opengl3.cpp.o
.PHONY : externals/imgui/imgui_impl_opengl3.cpp.o

externals/imgui/imgui_impl_opengl3.i: externals/imgui/imgui_impl_opengl3.cpp.i
.PHONY : externals/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
externals/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_impl_opengl3.cpp.i
.PHONY : externals/imgui/imgui_impl_opengl3.cpp.i

externals/imgui/imgui_impl_opengl3.s: externals/imgui/imgui_impl_opengl3.cpp.s
.PHONY : externals/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
externals/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_impl_opengl3.cpp.s
.PHONY : externals/imgui/imgui_impl_opengl3.cpp.s

externals/imgui/imgui_widgets.o: externals/imgui/imgui_widgets.cpp.o
.PHONY : externals/imgui/imgui_widgets.o

# target to build an object file
externals/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_widgets.cpp.o
.PHONY : externals/imgui/imgui_widgets.cpp.o

externals/imgui/imgui_widgets.i: externals/imgui/imgui_widgets.cpp.i
.PHONY : externals/imgui/imgui_widgets.i

# target to preprocess a source file
externals/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_widgets.cpp.i
.PHONY : externals/imgui/imgui_widgets.cpp.i

externals/imgui/imgui_widgets.s: externals/imgui/imgui_widgets.cpp.s
.PHONY : externals/imgui/imgui_widgets.s

# target to generate assembly for a file
externals/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/externals/imgui/imgui_widgets.cpp.s
.PHONY : externals/imgui/imgui_widgets.cpp.s

src/externals/glfw_implementation/glfw.o: src/externals/glfw_implementation/glfw.cpp.o
.PHONY : src/externals/glfw_implementation/glfw.o

# target to build an object file
src/externals/glfw_implementation/glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/externals/glfw_implementation/glfw.cpp.o
.PHONY : src/externals/glfw_implementation/glfw.cpp.o

src/externals/glfw_implementation/glfw.i: src/externals/glfw_implementation/glfw.cpp.i
.PHONY : src/externals/glfw_implementation/glfw.i

# target to preprocess a source file
src/externals/glfw_implementation/glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/externals/glfw_implementation/glfw.cpp.i
.PHONY : src/externals/glfw_implementation/glfw.cpp.i

src/externals/glfw_implementation/glfw.s: src/externals/glfw_implementation/glfw.cpp.s
.PHONY : src/externals/glfw_implementation/glfw.s

# target to generate assembly for a file
src/externals/glfw_implementation/glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/externals/glfw_implementation/glfw.cpp.s
.PHONY : src/externals/glfw_implementation/glfw.cpp.s

src/nvisii/camera.o: src/nvisii/camera.cpp.o
.PHONY : src/nvisii/camera.o

# target to build an object file
src/nvisii/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/camera.cpp.o
.PHONY : src/nvisii/camera.cpp.o

src/nvisii/camera.i: src/nvisii/camera.cpp.i
.PHONY : src/nvisii/camera.i

# target to preprocess a source file
src/nvisii/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/camera.cpp.i
.PHONY : src/nvisii/camera.cpp.i

src/nvisii/camera.s: src/nvisii/camera.cpp.s
.PHONY : src/nvisii/camera.s

# target to generate assembly for a file
src/nvisii/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/camera.cpp.s
.PHONY : src/nvisii/camera.cpp.s

src/nvisii/entity.o: src/nvisii/entity.cpp.o
.PHONY : src/nvisii/entity.o

# target to build an object file
src/nvisii/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/entity.cpp.o
.PHONY : src/nvisii/entity.cpp.o

src/nvisii/entity.i: src/nvisii/entity.cpp.i
.PHONY : src/nvisii/entity.i

# target to preprocess a source file
src/nvisii/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/entity.cpp.i
.PHONY : src/nvisii/entity.cpp.i

src/nvisii/entity.s: src/nvisii/entity.cpp.s
.PHONY : src/nvisii/entity.s

# target to generate assembly for a file
src/nvisii/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/entity.cpp.s
.PHONY : src/nvisii/entity.cpp.s

src/nvisii/light.o: src/nvisii/light.cpp.o
.PHONY : src/nvisii/light.o

# target to build an object file
src/nvisii/light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/light.cpp.o
.PHONY : src/nvisii/light.cpp.o

src/nvisii/light.i: src/nvisii/light.cpp.i
.PHONY : src/nvisii/light.i

# target to preprocess a source file
src/nvisii/light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/light.cpp.i
.PHONY : src/nvisii/light.cpp.i

src/nvisii/light.s: src/nvisii/light.cpp.s
.PHONY : src/nvisii/light.s

# target to generate assembly for a file
src/nvisii/light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/light.cpp.s
.PHONY : src/nvisii/light.cpp.s

src/nvisii/material.o: src/nvisii/material.cpp.o
.PHONY : src/nvisii/material.o

# target to build an object file
src/nvisii/material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/material.cpp.o
.PHONY : src/nvisii/material.cpp.o

src/nvisii/material.i: src/nvisii/material.cpp.i
.PHONY : src/nvisii/material.i

# target to preprocess a source file
src/nvisii/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/material.cpp.i
.PHONY : src/nvisii/material.cpp.i

src/nvisii/material.s: src/nvisii/material.cpp.s
.PHONY : src/nvisii/material.s

# target to generate assembly for a file
src/nvisii/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/material.cpp.s
.PHONY : src/nvisii/material.cpp.s

src/nvisii/mesh.o: src/nvisii/mesh.cpp.o
.PHONY : src/nvisii/mesh.o

# target to build an object file
src/nvisii/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/mesh.cpp.o
.PHONY : src/nvisii/mesh.cpp.o

src/nvisii/mesh.i: src/nvisii/mesh.cpp.i
.PHONY : src/nvisii/mesh.i

# target to preprocess a source file
src/nvisii/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/mesh.cpp.i
.PHONY : src/nvisii/mesh.cpp.i

src/nvisii/mesh.s: src/nvisii/mesh.cpp.s
.PHONY : src/nvisii/mesh.s

# target to generate assembly for a file
src/nvisii/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/mesh.cpp.s
.PHONY : src/nvisii/mesh.cpp.s

src/nvisii/nvisii.o: src/nvisii/nvisii.cpp.o
.PHONY : src/nvisii/nvisii.o

# target to build an object file
src/nvisii/nvisii.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/nvisii.cpp.o
.PHONY : src/nvisii/nvisii.cpp.o

src/nvisii/nvisii.i: src/nvisii/nvisii.cpp.i
.PHONY : src/nvisii/nvisii.i

# target to preprocess a source file
src/nvisii/nvisii.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/nvisii.cpp.i
.PHONY : src/nvisii/nvisii.cpp.i

src/nvisii/nvisii.s: src/nvisii/nvisii.cpp.s
.PHONY : src/nvisii/nvisii.s

# target to generate assembly for a file
src/nvisii/nvisii.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/nvisii.cpp.s
.PHONY : src/nvisii/nvisii.cpp.s

src/nvisii/nvisii_import_scene.o: src/nvisii/nvisii_import_scene.cpp.o
.PHONY : src/nvisii/nvisii_import_scene.o

# target to build an object file
src/nvisii/nvisii_import_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/nvisii_import_scene.cpp.o
.PHONY : src/nvisii/nvisii_import_scene.cpp.o

src/nvisii/nvisii_import_scene.i: src/nvisii/nvisii_import_scene.cpp.i
.PHONY : src/nvisii/nvisii_import_scene.i

# target to preprocess a source file
src/nvisii/nvisii_import_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/nvisii_import_scene.cpp.i
.PHONY : src/nvisii/nvisii_import_scene.cpp.i

src/nvisii/nvisii_import_scene.s: src/nvisii/nvisii_import_scene.cpp.s
.PHONY : src/nvisii/nvisii_import_scene.s

# target to generate assembly for a file
src/nvisii/nvisii_import_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/nvisii_import_scene.cpp.s
.PHONY : src/nvisii/nvisii_import_scene.cpp.s

src/nvisii/texture.o: src/nvisii/texture.cpp.o
.PHONY : src/nvisii/texture.o

# target to build an object file
src/nvisii/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/texture.cpp.o
.PHONY : src/nvisii/texture.cpp.o

src/nvisii/texture.i: src/nvisii/texture.cpp.i
.PHONY : src/nvisii/texture.i

# target to preprocess a source file
src/nvisii/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/texture.cpp.i
.PHONY : src/nvisii/texture.cpp.i

src/nvisii/texture.s: src/nvisii/texture.cpp.s
.PHONY : src/nvisii/texture.s

# target to generate assembly for a file
src/nvisii/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/texture.cpp.s
.PHONY : src/nvisii/texture.cpp.s

src/nvisii/transform.o: src/nvisii/transform.cpp.o
.PHONY : src/nvisii/transform.o

# target to build an object file
src/nvisii/transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/transform.cpp.o
.PHONY : src/nvisii/transform.cpp.o

src/nvisii/transform.i: src/nvisii/transform.cpp.i
.PHONY : src/nvisii/transform.i

# target to preprocess a source file
src/nvisii/transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/transform.cpp.i
.PHONY : src/nvisii/transform.cpp.i

src/nvisii/transform.s: src/nvisii/transform.cpp.s
.PHONY : src/nvisii/transform.s

# target to generate assembly for a file
src/nvisii/transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/transform.cpp.s
.PHONY : src/nvisii/transform.cpp.s

src/nvisii/volume.o: src/nvisii/volume.cpp.o
.PHONY : src/nvisii/volume.o

# target to build an object file
src/nvisii/volume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/volume.cpp.o
.PHONY : src/nvisii/volume.cpp.o

src/nvisii/volume.i: src/nvisii/volume.cpp.i
.PHONY : src/nvisii/volume.i

# target to preprocess a source file
src/nvisii/volume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/volume.cpp.i
.PHONY : src/nvisii/volume.cpp.i

src/nvisii/volume.s: src/nvisii/volume.cpp.s
.PHONY : src/nvisii/volume.s

# target to generate assembly for a file
src/nvisii/volume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvisii_lib.dir/build.make CMakeFiles/nvisii_lib.dir/src/nvisii/volume.cpp.s
.PHONY : src/nvisii/volume.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... nvisii_swig_compilation"
	@echo "... adv_optix7course"
	@echo "... assimp"
	@echo "... generator"
	@echo "... glfw"
	@echo "... int01-simpleTriangles"
	@echo "... int06-rtow-mixedGeometries"
	@echo "... int10-texturedTriangles"
	@echo "... int11-rotatingBoxes"
	@echo "... int12-switchingTextureSets"
	@echo "... int13-motionBlurBoxes"
	@echo "... nvisii"
	@echo "... nvisii_lib"
	@echo "... owl_static"
	@echo "... owl_viewer"
	@echo "... sample00-rayGenOnly"
	@echo "... sample01-simpleTriangles"
	@echo "... sample05-rtow"
	@echo "... sample06-rtow-mixedGeometries"
	@echo "... sample07-rtow-multiGPU"
	@echo "... sample08-sierpinski"
	@echo "... sample09-motionBlurSimpleTriangles"
	@echo "... toneMap"
	@echo "... CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.o"
	@echo "... CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.i"
	@echo "... CMakeFiles/nvisii.dir/nvisiiPYTHON_wrap.s"
	@echo "... cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.o"
	@echo "... cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.i"
	@echo "... cuda_compile_ptx_1_generated_path_tracer.cu.ptx_embedded.s"
	@echo "... externals/glad/src/glad.o"
	@echo "... externals/glad/src/glad.i"
	@echo "... externals/glad/src/glad.s"
	@echo "... externals/imgui/ImCurveEdit.o"
	@echo "... externals/imgui/ImCurveEdit.i"
	@echo "... externals/imgui/ImCurveEdit.s"
	@echo "... externals/imgui/ImGradient.o"
	@echo "... externals/imgui/ImGradient.i"
	@echo "... externals/imgui/ImGradient.s"
	@echo "... externals/imgui/ImGuizmo.o"
	@echo "... externals/imgui/ImGuizmo.i"
	@echo "... externals/imgui/ImGuizmo.s"
	@echo "... externals/imgui/ImSequencer.o"
	@echo "... externals/imgui/ImSequencer.i"
	@echo "... externals/imgui/ImSequencer.s"
	@echo "... externals/imgui/imgui.o"
	@echo "... externals/imgui/imgui.i"
	@echo "... externals/imgui/imgui.s"
	@echo "... externals/imgui/imgui_demo.o"
	@echo "... externals/imgui/imgui_demo.i"
	@echo "... externals/imgui/imgui_demo.s"
	@echo "... externals/imgui/imgui_draw.o"
	@echo "... externals/imgui/imgui_draw.i"
	@echo "... externals/imgui/imgui_draw.s"
	@echo "... externals/imgui/imgui_impl_glfw.o"
	@echo "... externals/imgui/imgui_impl_glfw.i"
	@echo "... externals/imgui/imgui_impl_glfw.s"
	@echo "... externals/imgui/imgui_impl_opengl3.o"
	@echo "... externals/imgui/imgui_impl_opengl3.i"
	@echo "... externals/imgui/imgui_impl_opengl3.s"
	@echo "... externals/imgui/imgui_widgets.o"
	@echo "... externals/imgui/imgui_widgets.i"
	@echo "... externals/imgui/imgui_widgets.s"
	@echo "... src/externals/glfw_implementation/glfw.o"
	@echo "... src/externals/glfw_implementation/glfw.i"
	@echo "... src/externals/glfw_implementation/glfw.s"
	@echo "... src/nvisii/camera.o"
	@echo "... src/nvisii/camera.i"
	@echo "... src/nvisii/camera.s"
	@echo "... src/nvisii/entity.o"
	@echo "... src/nvisii/entity.i"
	@echo "... src/nvisii/entity.s"
	@echo "... src/nvisii/light.o"
	@echo "... src/nvisii/light.i"
	@echo "... src/nvisii/light.s"
	@echo "... src/nvisii/material.o"
	@echo "... src/nvisii/material.i"
	@echo "... src/nvisii/material.s"
	@echo "... src/nvisii/mesh.o"
	@echo "... src/nvisii/mesh.i"
	@echo "... src/nvisii/mesh.s"
	@echo "... src/nvisii/nvisii.o"
	@echo "... src/nvisii/nvisii.i"
	@echo "... src/nvisii/nvisii.s"
	@echo "... src/nvisii/nvisii_import_scene.o"
	@echo "... src/nvisii/nvisii_import_scene.i"
	@echo "... src/nvisii/nvisii_import_scene.s"
	@echo "... src/nvisii/texture.o"
	@echo "... src/nvisii/texture.i"
	@echo "... src/nvisii/texture.s"
	@echo "... src/nvisii/transform.o"
	@echo "... src/nvisii/transform.i"
	@echo "... src/nvisii/transform.s"
	@echo "... src/nvisii/volume.o"
	@echo "... src/nvisii/volume.i"
	@echo "... src/nvisii/volume.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

